apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../security/default-deny.yaml
  - ../../secrets/secretproviderclass-vault.yaml
  - ../../security/istio-mtls.yaml
  - ../../security/serviceaccounts.yaml

# commonLabels could be added as needed
