{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atonixcorp-platform.fullname" . }}-backend-secret
type: Opaque
stringData:
  SECRET_KEY: "{{ .Values.backend.env.SECRET_KEY }}"
  DATABASE_URL: "{{ .Values.backend.env.DATABASE_URL }}"
{{- end }}
