apiVersion: v1
kind: Secret
metadata:
  name: concourse-secrets
  namespace: concourse
type: Opaque
stringData:
  # Set strong values before applying
  postgres-password: "concourse_pass"
  minio-root-user: "atonixadmin"
  minio-root-password: "atonix2024!"
  admin-password: "atonix2024!"
