apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: concourse-ingress
  namespace: concourse
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: concourse.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: concourse-web
                port:
                  number: 8080
    - host: jaeger.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaeger
                port:
                  number: 16686
