apiVersion: cache.atonixcorp.com/v1alpha1
kind: Atonixcorp
metadata:
  labels:
    app.kubernetes.io/name: atonixcorp-operator
    app.kubernetes.io/managed-by: kustomize
  name: atonixcorp-sample
spec:
  # TODO(user): Add fields here
