apiVersion: v1
kind: Pod
metadata:
  name: test-pvc-binding
<<<<<<< HEAD
  namespace: atonixcorp
=======
  namespace: atonixcorp
>>>>>>> 12bd998bda7cee255affa733e542706dbab8dcfb
spec:
  containers:
  - name: test
    image: busybox
    command: ['sleep', '300']
    volumeMounts:
    - name: postgresql-data
      mountPath: /data
    - name: redis-data
      mountPath: /redis
  volumes:
  - name: postgresql-data
    persistentVolumeClaim:
<<<<<<< HEAD
      claimName: atonixcorp-dev-postgresql-data
  - name: redis-data
    persistentVolumeClaim:
      claimName: atonixcorp-dev-redis-data
=======
      claimName: atonixcorp-dev-postgresql-data
  - name: redis-data
    persistentVolumeClaim:
      claimName: atonixcorp-dev-redis-data
>>>>>>> 12bd998bda7cee255affa733e542706dbab8dcfb
