apiVersion: v1
kind: Service
metadata:
  name: atonixcorp-frontend
  namespace: atonixcorp
  labels:
    app: atonixcorp-frontend
spec:
  selector:
    app: atonixcorp-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: ClusterIP
