apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atonixcorp-ingress
  namespace: atonixcorp
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: atonixcorp.org
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: atonixcorp-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atonixcorp-frontend
                port:
                  number: 80
    - host: api.atonixcorp.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atonixcorp-backend
                port:
                  number: 8000
