apiVersion: v1
kind: Service
metadata:
  name: atonixcorp
  namespace: atonixcorp
  labels:
    app: atonixcorp
spec:
  selector:
    app: atonixcorp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
