apiVersion: v1
kind: Secret
metadata:
  name: atonixcorp-secrets
  namespace: atonixcorp
type: Opaque
stringData:
  SECRET_KEY: "REPLACE_ME_WITH_A_SECRET"
  POSTGRES_DB: "atonixcorp"
  POSTGRES_USER: "atonixcorp_user"
  POSTGRES_PASSWORD: "atonixcorp_password"
