apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: atonixcorp-com-cert
  namespace: atonixcorp
spec:
  secretName: atonixcorp-com-tls
  dnsNames:
  - api.atonixcorp.com
  - www.atonixcorp.com
  - atonixcorp.com
  issuerRef:
    name: letsencrypt-dns-cloudflare-staging
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 2048
  commonName: atonixcorp.com
