apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-route53-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@atonixcorp.org
    privateKeySecretRef:
      name: letsencrypt-dns-route53-staging-key
    solvers:
    - dns01:
        route53:
          region: us-east-1
          accessKeyID: "<AWS_ACCESS_KEY_ID>"
          secretAccessKeySecretRef:
            name: route53-credentials
            key: secret-access-key
