apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@atonixcorp.com
    privateKeySecretRef:
      name: letsencrypt-http-staging-key
    solvers:
    - http01:
        ingress:
          class: nginx
