apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atonixcorp-security
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/atonixcorp/atonixcorp'
    targetRevision: HEAD
    path: k8s/overlays/security
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: atonixcorp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
