apiVersion: v1
kind: Secret
metadata:
  name: pipeline-registry-secret
  namespace: atonixcorp-tekton
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
    tekton.dev/docker-1: https://gitlab.com
    tekton.dev/docker-2: https://ghcr.io
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{BASE64_DOCKERCONFIG_JSON}}