apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-core.fullname" . }}
  labels:
    {{- include "kube-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.ipFamilies }}
  # ipFamilies and ipFamilyPolicy allow chart users to opt into dual-stack Services
  ipFamilies:
  {{- toYaml .Values.service.ipFamilies | nindent 2 }}
  ipFamilyPolicy: {{ default "PreferDualStack" .Values.service.ipFamilyPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kube-core.selectorLabels" . | nindent 4 }}
