apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: atonixcorp-tls-selfsigned
  namespace: atonixcorp
spec:
  secretName: atonixcorp-tls-selfsigned
  duration: 2160h # 90d
  renewBefore: 360h
  subject:
    organizations:
    - AtonixCorp
  dnsNames:
  - atonixcorp.com
  - www.atonixcorp.com
  - api.atonixcorp.com
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
