apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - atonixcorp-postgres.yaml
  - fast-ssd-postgres-pv.yaml
  - atonixcorp-redis.yaml
  - atonixcorp-backend.yaml
  - atonixcorp-frontend.yaml
  - atonixcorp-celery.yaml
  - atonixcorp-ingress.yaml
