apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
<<<<<<< HEAD
- namespace.yaml
- postgres.yaml
- redis.yaml
- backend.yaml
- frontend.yaml
- celery.yaml
- ingress.yaml
=======
  - namespace.yaml
  - atonixcorp-postgres.yaml
  - fast-ssd-postgres-pv.yaml
  - atonixcorp-redis.yaml
  - atonixcorp-backend.yaml
  - atonixcorp-frontend.yaml
  - atonixcorp-celery.yaml
  - atonixcorp-ingress.yaml
>>>>>>> 12bd998bda7cee255affa733e542706dbab8dcfb
