apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-dns-cloudflare
spec:
  acme:
    # Use Let's Encrypt staging to avoid rate limits while testing
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@atonixcorp.org
    privateKeySecretRef:
      name: letsencrypt-staging-dns-cloudflare-key
    solvers:
    - dns01:
        cloudflare:
          # The secretName below must contain your Cloudflare API token under key "api-token"
          email: admin@atonixcorp.org
          apiTokenSecretRef:
            name: cf-api-token-secret
            key: api-token
