apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: ipv4-pool
      protocol: layer2
      addresses:
      - 192.168.1.240-192.168.1.250
    - name: ipv6-pool
      protocol: layer2
      addresses:
      - fd00:abcd::100-fd00:abcd::120
