apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - local-pvs.yaml

patchesStrategicMerge:
  - patch-backend-image.yaml
  - patch-backend-init-image.yaml
  - patch-frontend-image.yaml
  - patch-celery-image.yaml
  - ingress-patch.yaml
  - toleration-backend.yaml
  - toleration-frontend.yaml
  - toleration-postgres.yaml
  - toleration-redis.yaml
  - toleration-celery.yaml
  - toleration-flower.yaml
